SHOW DATABASES;

USE dbms31052022;

CREATE TABLE customers (
    CustomerID VARCHAR(5) NOT NULL PRIMARY KEY,
    CompanyName VARCHAR(40) NOT NULL,
    ContactName VARCHAR(30) DEFAULT NULL,
    ContactTitle VARCHAR(30) DEFAULT NULL,
    Address VARCHAR(60) DEFAULT NULL,
    City VARCHAR(15) DEFAULT NULL,
    Region VARCHAR(15) DEFAULT NULL,
    PostalCode VARCHAR(10) DEFAULT NULL,
    Country VARCHAR(15) DEFAULT NULL,
    Phone VARCHAR(24) DEFAULT NULL,
    Fax VARCHAR(24) DEFAULT NULL
);

CREATE TABLE employees (
    EmployeeID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    LastName VARCHAR(20) NOT NULL,
    FirstName VARCHAR(10) NOT NULL,
    JobTitle VARCHAR(30) DEFAULT NULL,
    BirthDate DATETIME DEFAULT NULL,
    HireDate DATETIME DEFAULT NULL,
    Address VARCHAR(60) DEFAULT NULL,
    City VARCHAR(15) DEFAULT NULL,
    PostalCode VARCHAR(10) DEFAULT NULL,
    Country VARCHAR(15) DEFAULT NULL,
    Phone VARCHAR(24) DEFAULT NULL,
    ReportsTo INT(11) DEFAULT NULL,
    Salary FLOAT DEFAULT NULL
);

CREATE TABLE orders (
    OrderID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CustomerID VARCHAR(5) DEFAULT NULL,
    EmployeeID INT(11) DEFAULT NULL,
    OrderDate DATETIME DEFAULT NULL,
    RequiredDate DATETIME DEFAULT NULL,
    ShippedDate DATETIME DEFAULT NULL,
    ShipID INT(11) DEFAULT NULL,
    ShipName VARCHAR(40) DEFAULT NULL,
    ShipAddress VARCHAR(60) DEFAULT NULL
);

CREATE TABLE categories (
    CategoryID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CategoryName VARCHAR(15) NOT NULL
);

CREATE TABLE products (
    ProductID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ProductName VARCHAR(40) NOT NULL,
    SupplierID INT(11) DEFAULT NULL,
    CategoryID INT(11) DEFAULT NULL,
    QuantityPerUnit VARCHAR(20) DEFAULT NULL,
    UnitPrice DECIMAL(10, 4) DEFAULT 0.0000,
    UnitsInStock SMALLINT(2) DEFAULT 0,
    UnitsOnOrder SMALLINT(2) DEFAULT 0,
    ReorderLevel SMALLINT(2) DEFAULT 0,
    Discontinued BIT(1) NOT NULL DEFAULT 0
);

CREATE TABLE shippers (
    ShipperID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CompanyName VARCHAR(40) NOT NULL,
    Phone VARCHAR(24) DEFAULT NULL
);

CREATE TABLE suppliers (
    SupplierID INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CompanyName VARCHAR(40) NOT NULL,
    ContactName VARCHAR(30) DEFAULT NULL,
    ContactJobTitle VARCHAR(30) DEFAULT NULL,
    Address VARCHAR(60) DEFAULT NULL,
    Phone VARCHAR(24) DEFAULT NULL
);

CREATE TABLE orderdetails (
    OrderID INT(11) NOT NULL,
    ProductID INT(11) NOT NULL,
    UnitPrice DECIMAL(10, 4) NOT NULL DEFAULT 0.0000,
    Quantity SMALLINT(2) NOT NULL DEFAULT 1,
    PRIMARY KEY (OrderID, ProductID)
);

DESC customers;

DESC employees;

DESC orders;

DESC categories;

DESC products;

DESC shippers;

DESC suppliers;

DESC orderdetails;